secrets:
  database:
    url: ${{DATABASE_URL}}
    password: ${{DATABASE_PASSWORD}}
    user: ${{DATABASE_USER}}
  api:
    secret_key: ${{API_SECRET_KEY}}
    jwt_secret: ${{JWT_SECRET}}
  external_services: {}
  storage:
    connection_string: ${{TEST_STORE_CONNECTION_STRING}}
    credentials: ${{TEST_STORE_CREDENTIALS}}
environment_mapping:
  development:
    DATABASE_URL: postgresql://postgres:${{DATABASE_PASSWORD}}@localhost:5432/dev_db
    API_SECRET_KEY: ${{API_SECRET_KEY}}
    REDIS_URL: redis://:${{REDIS_PASSWORD}}@localhost:6379/0
  staging:
    DATABASE_URL: ${{STAGING_DATABASE_URL}}
    API_SECRET_KEY: ${{STAGING_API_SECRET_KEY}}
    REDIS_URL: ${{STAGING_REDIS_URL}}
  production:
    DATABASE_URL: ${{PROD_DATABASE_URL}}
    API_SECRET_KEY: ${{PROD_API_SECRET_KEY}}
    REDIS_URL: ${{PROD_REDIS_URL}}
