# Multi-Agent Project Configuration V2 - Real Isolation
# Copy this to config.yaml and customize

project_name: "fix_functional_validation"
description: "Fix autocoder functional validation from 50% to 100% success rate"

# Phases definition
phases:
  - name: "fix_blueprint_generation"
    description: "Fix blueprint generation to create all required endpoints properly"
  - name: "fix_v5_integration"
    description: "Fix V5 database integration endpoint issues"
  - name: "verify_100_percent_success"
    description: "Verify all functional tests achieve 100% success rate"

# Isolation settings
isolation:
  shared_evidence_dir: "shared/evidence"
  implementation_context: |
    # Implementation Agent Context
    You are an implementation agent working in isolation.
    Your task is defined in instructions.md.
    Store all outputs in ../shared/evidence/
  evaluation_context: |
    # Evaluation Agent Context  
    You are an evaluation agent working in isolation.
    Your task is defined in evaluation.md.
    Examine evidence in ./evidence/ directory.
    Provide objective PASS/FAIL assessment.